#push image to docker hub and ecr on push to main branh
name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      # push to ECR
      - name: Build and push the Docker image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          rev=$(git rev-parse --short HEAD)
          docker build . -t hagu021
          docker tag hagu021 244530008913.dkr.ecr.eu-west-1.amazonaws.com/hagu021/docker-container:$rev
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/hagu021/docker-container:$rev
      
      # Docker Hub login and push for Docker Hub 
      - name: Log in to Docker Hub and push image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker tag hagu021 hagu021/image:latest
          docker push hagu021/image:latest